language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
  - client/node_modules
install:
- npm install
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: heroku
  app: aischat
  api_key:
    secure: s64Qbc05mWyWd3cH1GIGnpQE6vQz5RyRDuFL8E1LAoeyzSAFE5Flk18bkUh29uah2ujEGrdCzx5RhcvKO/+8DGtRooZFqiI9/2q7JMpnWfYU8LxxmeEPYNHF9DodLqnxK2CuXiqszJ8yXyoUgJPbu2d9ls5F/3hUCd0fc2QQqef+PRb0hQIeUpJQF5C8yesJF60WVb6/4s1/xy160HAref3wFhR7Ov07rsRH0Ow8g8FXVgdthjX0ucjU9I/EAlsQ/OY0ooe1Sx395ni9xs0GaDApM3hFzBtI4+o3HzwCMRwPN5jI8GJFrrUVUjIIJRSYYB6GUQhwwQ/OXuAwtUsqkBzaGcnOi0W6PfXzBWIXFIO6Hgt2RNotoe4zDMZbc7xTRi+7m6OwB6bhTiG1SnETWVDfUzIZQdCObmgY7OHISuy84pF26OG+Vpmh2Es/EBUjGsnnGUtmPFpy0/EN6C15oaAwhmT3qGDSkk74E/sOQVILY6BQMG10/6gEhHmLXmV+eUbzhacwcEV57SXpbWn+bsUnAboACNtUf+XTLzWIwU6cqk+JClFslNAidHJQpAPfE7MuHkE5I3eI8tgU4HWsW90h0UOxfl5ektjCZRszU23SsUWBRvynY7CmfUEyZd7kYqVOtyuuNfnmZkp/fSyQzgjlW6GPuK+7Knwwx93vpF0=
