language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: heroku
  app: ais-chat
  api_key:
    secure: cqto1ez3yZD7i2nUbGIxDvKmIX8IXDaGlRP5D4GVr2XY4CcJ6pFMJjb3ofs/PWoZTycQp2u1ovSl2qH7utWszmwSnMBWDwTpItAEWvqr8t+LbiGyq0IF2RA6WF/+NbFAoxC28cb4YCEROV0gR2HjixdgCcFCT83QAZNIPpK+ui+uqDqpDI33IcrkMdrbRK6rIEN4xzn4xUCDmX3jd05fGr1AuLwSt/aRTocMWJWPOsOiucfnkgtF559o/wRqfJC7ZHotLGFKCGtBhKgjVEAd9Egv9ELCbyJS3r/ooF05owvSrFq2HOazp8d4swYpodF/QRYUhX3TNdRIuB+iqbqpv8ULsrYuD81o31yZGBG9/qLn9tMKK3cHFFU8sZuEiKr74UHrNE23qzTvzLz0vnx9cOmgNnuoipD9UmvmTaBfj6LHbUXBUFHXNwCMymvrQcMJUjT4j59d8fqqXT1+dL5mWRs0CZ54YlO8GOoq2rx4yF7b+TaHcpIKulGiQvyQhOo8pVfrsLoOMAdAtHIKYFmdQdMcmzxZXwquWDCdySdOvuwoqRt+2f46MS2ex4gBHGpbBQZIaTYlvEUqqMxY7rZoaDtu2MqypvwIcojtp/9QYeUsno7cBwnpPydKjqr3Et2ofp9bOchmvEZnhaxv0UhGu16RXa67JHfP7NcESkOmvws=
